/*
 *
 * Copyright (c) 2014 Todd Kover
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

\set ON_ERROR_STOP

 ALTER TABLE ACCOUNT_REALM_COMPANY DROP CONSTRAINT FK_ACCT_RLM_CMPY_CMPY_ID;
 ALTER TABLE ACCOUNT_REALM_COMPANY 
	ADD CONSTRAINT FK_ACCT_RLM_CMPY_CMPY_ID FOREIGN KEY (COMPANY_ID) 
	REFERENCES COMPANY (COMPANY_ID)  DEFERRABLE  INITIALLY IMMEDIATE;

 ALTER TABLE CIRCUIT DROP CONSTRAINT FK_CIRCUIT_VEND_COMPANYID;
 ALTER TABLE CIRCUIT
	ADD CONSTRAINT FK_CIRCUIT_VEND_COMPANYID FOREIGN KEY (VENDOR_COMPANY_ID)
	REFERENCES COMPANY (COMPANY_ID)  DEFERRABLE  INITIALLY IMMEDIATE;

 ALTER TABLE CIRCUIT DROP CONSTRAINT FK_CIRCUIT_ALOC_COMPANYID;
 ALTER TABLE CIRCUIT
	ADD CONSTRAINT FK_CIRCUIT_ALOC_COMPANYID FOREIGN KEY (ALOC_LEC_COMPANY_ID)
	REFERENCES COMPANY (COMPANY_ID)  DEFERRABLE  INITIALLY IMMEDIATE;

 ALTER TABLE CIRCUIT DROP CONSTRAINT FK_CIRCUIT_ZLOC_COMPANY_ID;
 ALTER TABLE CIRCUIT
	ADD CONSTRAINT FK_CIRCUIT_ZLOC_COMPANY_ID FOREIGN KEY (ZLOC_LEC_COMPANY_ID)
	REFERENCES COMPANY (COMPANY_ID)  DEFERRABLE  INITIALLY IMMEDIATE;

 ALTER TABLE COMPANY DROP CONSTRAINT FK_COMPANY_PARENT_COMPANY_ID;
 ALTER TABLE COMPANY
	ADD CONSTRAINT FK_COMPANY_PARENT_COMPANY_ID FOREIGN KEY (PARENT_COMPANY_ID)
	REFERENCES COMPANY (COMPANY_ID)  DEFERRABLE  INITIALLY IMMEDIATE;

 ALTER TABLE COMPANY_TYPE DROP CONSTRAINT FK_COMPANY_TYPE_COMPANY_ID;
 ALTER TABLE COMPANY_TYPE
	ADD CONSTRAINT FK_COMPANY_TYPE_COMPANY_ID FOREIGN KEY (COMPANY_ID)
	REFERENCES COMPANY (COMPANY_ID)  DEFERRABLE  INITIALLY IMMEDIATE;

 ALTER TABLE CONTRACT DROP CONSTRAINT FK_CONTRACT_COMPANY_ID;
 ALTER TABLE CONTRACT
	ADD CONSTRAINT FK_CONTRACT_COMPANY_ID FOREIGN KEY (COMPANY_ID)
	REFERENCES COMPANY (COMPANY_ID)  DEFERRABLE  INITIALLY IMMEDIATE;

 ALTER TABLE DEPARTMENT DROP CONSTRAINT FK_DEPT_COMPANY;
 ALTER TABLE DEPARTMENT
	ADD CONSTRAINT FK_DEPT_COMPANY FOREIGN KEY (COMPANY_ID)
	REFERENCES COMPANY (COMPANY_ID)  DEFERRABLE  INITIALLY IMMEDIATE  ;

 ALTER TABLE DEVICE DROP CONSTRAINT FK_DEVICE_COMPANY__ID;
 ALTER TABLE DEVICE
	ADD CONSTRAINT FK_DEVICE_COMPANY__ID FOREIGN KEY (COMPANY_ID)
	REFERENCES COMPANY (COMPANY_ID)  DEFERRABLE  INITIALLY IMMEDIATE;

 ALTER TABLE DEVICE_TYPE DROP CONSTRAINT FK_DEVTYP_COMPANY;
 ALTER TABLE DEVICE_TYPE
	ADD CONSTRAINT FK_DEVTYP_COMPANY FOREIGN KEY (COMPANY_ID)
	REFERENCES COMPANY (COMPANY_ID)  DEFERRABLE  INITIALLY IMMEDIATE;

 ALTER TABLE NETBLOCK DROP CONSTRAINT FK_NETBLOCK_COMPANY;
 ALTER TABLE NETBLOCK
	ADD CONSTRAINT FK_NETBLOCK_COMPANY FOREIGN KEY (NIC_COMPANY_ID)
	REFERENCES COMPANY (COMPANY_ID)  DEFERRABLE  INITIALLY IMMEDIATE;

 ALTER TABLE OPERATING_SYSTEM DROP CONSTRAINT FK_OS_COMPANY;
 ALTER TABLE OPERATING_SYSTEM
	ADD CONSTRAINT FK_OS_COMPANY FOREIGN KEY (COMPANY_ID)
	REFERENCES COMPANY (COMPANY_ID)  DEFERRABLE  INITIALLY IMMEDIATE;

 ALTER TABLE PERSON_COMPANY DROP CONSTRAINT FK_PERSON_COMPANY_COMPANY_ID;
 ALTER TABLE PERSON_COMPANY
	ADD CONSTRAINT FK_PERSON_COMPANY_COMPANY_ID FOREIGN KEY (COMPANY_ID)
	REFERENCES COMPANY (COMPANY_ID)  DEFERRABLE  INITIALLY IMMEDIATE;

 ALTER TABLE PERSON_CONTACT DROP CONSTRAINT FK_PRSN_CONTECT_CR_CMPYID;
 ALTER TABLE PERSON_CONTACT
	ADD CONSTRAINT FK_PRSN_CONTECT_CR_CMPYID FOREIGN KEY (PERSON_CONTACT_CR_COMPANY_ID)
	REFERENCES COMPANY (COMPANY_ID)  DEFERRABLE  INITIALLY IMMEDIATE;

 ALTER TABLE PHYSICAL_ADDRESS DROP CONSTRAINT FK_PHYSADDR_COMPANY_ID;
 ALTER TABLE PHYSICAL_ADDRESS
	ADD CONSTRAINT FK_PHYSADDR_COMPANY_ID FOREIGN KEY (COMPANY_ID)
	REFERENCES COMPANY (COMPANY_ID)  DEFERRABLE  INITIALLY IMMEDIATE;

 ALTER TABLE PROPERTY DROP CONSTRAINT FK_PROPERTY_COMPID;
 ALTER TABLE PROPERTY
	ADD CONSTRAINT FK_PROPERTY_COMPID FOREIGN KEY (COMPANY_ID)
	REFERENCES COMPANY (COMPANY_ID)  DEFERRABLE  INITIALLY IMMEDIATE;

 ALTER TABLE PROPERTY DROP CONSTRAINT FK_PROPERTY_PVAL_COMPID;
 ALTER TABLE PROPERTY
	ADD CONSTRAINT FK_PROPERTY_PVAL_COMPID FOREIGN KEY (PROPERTY_VALUE_COMPANY_ID)
	REFERENCES COMPANY (COMPANY_ID)  DEFERRABLE  INITIALLY IMMEDIATE;

 ALTER TABLE SITE DROP CONSTRAINT FK_SITE_COLO_COMPANY_ID;
 ALTER TABLE SITE
	ADD CONSTRAINT FK_SITE_COLO_COMPANY_ID FOREIGN KEY (COLO_COMPANY_ID)
	REFERENCES COMPANY (COMPANY_ID)  DEFERRABLE  INITIALLY IMMEDIATE;

 ALTER TABLE PERSON_ACCOUNT_REALM_COMPANY 
	DROP CONSTRAINT FK_AC_AC_RLM_CPY_ACT_RLM_CPY;
 ALTER TABLE PERSON_ACCOUNT_REALM_COMPANY
       ADD CONSTRAINT FK_AC_AC_RLM_CPY_ACT_RLM_CPY 
	FOREIGN KEY (ACCOUNT_REALM_ID, COMPANY_ID) 
	REFERENCES ACCOUNT_REALM_COMPANY (ACCOUNT_REALM_ID, COMPANY_ID)  
	DEFERRABLE  INITIALLY IMMEDIATE;

-- kill IntegrityPackage
DROP FUNCTION IF EXISTS "IntegrityPackage"."InitNestLevel"();
DROP FUNCTION IF EXISTS "IntegrityPackage"."NextNestLevel"();
DROP FUNCTION IF EXISTS "IntegrityPackage"."PreviousNestLevel"();
DROP FUNCTION IF EXISTS IntegrityPackage"."GetNestLevel"();
DROP SCHEMA IF EXISTS "IntegrityPackage";

-- migrate per-user to per-account and give a genericy name 
alter table account_collection drop constraint "fk_acctcol_usrcoltyp";

WITH merge AS (
	SELECT  account_collection_id, account_id, login,
		account_collection_name
	FROM    account_collection
		INNER JOIN account_collection_account
			USING (account_collection_id)
		INNER JOIN account USING (account_id)
	WHERE   account_collection_type = 'per-account'
)  UPDATE account_collection ac
	SET account_collection_name =
		CONCAT(m.login, '_', m.account_id),
	account_collection_type = 'per-account'
FROM merge m
WHERE m.account_collection_id = ac.account_collection_Id;


update account_collection set account_collection_type = 'per-account'
where account_collection_type = 'per-user';

ALTER TABLE ACCOUNT_COLLECTION
	ADD CONSTRAINT FK_ACCTCOL_USRCOLTYP 
	FOREIGN KEY (ACCOUNT_COLLECTION_TYPE) 
	REFERENCES VAL_ACCOUNT_COLLECTION_TYPE (ACCOUNT_COLLECTION_TYPE)  ;

RAISE EXCEPTION 'Need to cleanup per-user stuff';

-- random queries related to sorting out all the automated/usertype stuff
delete from account_collection_account
where account_collection_id in (
	select account_collection_id
	from account_collection
	where account_collection_type in ('automated', 'usertype')
);
 
 delete from account_collection
where account_collection_id in (
	select account_collection_id
	from account_collection
	where account_collection_type in ('automated', 'usertype')
);
 
select * from account_collection
where account_collection_id in (
	select child_account_collection_id
	from account_collection_hier
) and account_collection_type='automated';
